# Word2Vec (Negative Sampling)

In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
from string import punctuation
import time

In [2]:
import nltk
from nltk.corpus import brown
from nltk.corpus import stopwords
from collections import Counter
import matplotlib
nltk.download('stopwords')
nltk.download('brown')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\swara\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package brown to
[nltk_data]     C:\Users\swara\AppData\Roaming\nltk_data...
[nltk_data]   Package brown is already up-to-date!


True

## 1. Load data

In [3]:
corpus = brown.sents()

In [4]:
stop_words = set(stopwords.words('english'))
corpus = [[word for word in sent if word.lower() not in stop_words] for sent in corpus]

# Remove punctuation from corpus
corpus = [[word for word in sent if word not in punctuation] for sent in corpus]

# Remove empty sentences
corpus = [sent for sent in corpus if len(sent) > 0]

# Remove sentences with less than 5 words
corpus = [sent for sent in corpus if len(sent) >= 5]

# Remove sentences with more than 20 words
corpus = [sent for sent in corpus if len(sent) <= 20]

# Remove rare words
word_freq = Counter([word for sent in corpus for word in sent])
corpus = [[word for word in sent if word_freq[word] > 5] for sent in corpus]

In [5]:
#2. numeralization
#find unique words
flatten = lambda l: [item for sublist in l for item in sublist]
#assign unique integer
vocabs = list(set(flatten(corpus))) #all the words we have in the system - <UNK>

In [6]:
#create handy mapping between integer and word
word2index = {v:idx for idx, v in enumerate(vocabs)}
word2index['dog']

2319

In [7]:
vocabs.append('<UNK>')
word2index['<UNK>'] = len(vocabs)

In [8]:
index2word = {v:k for k, v in word2index.items()}
index2word[5]

'Club'

## 2. Prepare train data

In [9]:
#create pairs of center word, and outside word

def random_batch(batch_size, corpus, window_size=2):

    skipgrams = []

    #loop each corpus
    for doc in corpus:
        #look from the 2nd word until second last word
        for i in range(window_size, len(doc) - window_size):
            #center word
            center = word2index[doc[i]]
            #outside words = rest of the words
            outside_start =  i - window_size
            outside_end =  i + window_size + 1

            for j in range(outside_start, outside_end):
                if i != j:  # Skip the center word
                    outside = word2index[doc[j]]
                    skipgrams.append([center, outside])
                
    random_index = np.random.choice(range(len(skipgrams)), batch_size, replace=False)
    
    inputs, labels = [], []
    for index in random_index:
        inputs.append([skipgrams[index][0]])
        labels.append([skipgrams[index][1]])
        
    return np.array(inputs), np.array(labels)
            
x, y = random_batch(2, corpus)

In [10]:
x.shape  #batch_size, 1

(2, 1)

In [11]:
x

array([[7878],
       [5447]])

In [12]:
y.shape  #batch_size 1

(2, 1)

## 3. Negative Sampling

### Unigram distribution

$$P(w)=U(w)^{3/4}/Z$$

In [13]:
z = 0.001

In [14]:
#count
from collections import Counter

word_count = Counter(flatten(corpus))
word_count

#get the total number of words
num_total_words = sum([c for w, c in word_count.items()])
num_total_words

356098

In [15]:
vocabs

['assumptions',
 'impossible',
 'Boys',
 'worn',
 'intellectual',
 'Club',
 'Market',
 'French',
 'rope',
 'however',
 'Turkish',
 'stared',
 'sponsored',
 'slipped',
 'proof',
 'age',
 'Dr.',
 'Colorado',
 'emotions',
 'earlier',
 'Nelson',
 'eloquent',
 'playing',
 'register',
 'concepts',
 'Monroe',
 'compiled',
 'One',
 'tremendous',
 'direction',
 'Publications',
 'ordinary',
 'C',
 'Chapel',
 'angle',
 'theology',
 'contributions',
 'era',
 'Academy',
 'vertical',
 'skin',
 'waving',
 'singers',
 'blunt',
 'live',
 'react',
 'Achievement',
 'adjust',
 'lump',
 'Youth',
 'theoretical',
 'springs',
 'selfish',
 'decides',
 'watercolor',
 'remind',
 'Turning',
 'slice',
 'lead',
 'travel',
 'sake',
 'Yes',
 'Joseph',
 'remark',
 'leaders',
 'surrendered',
 'Dumont',
 'supplied',
 'approaching',
 'honors',
 'camera',
 'university',
 'acted',
 'element',
 'neurotic',
 'match',
 'FBI',
 'filtered',
 'consistent',
 'phenomena',
 'brighter',
 'name',
 'H',
 'Gen.',
 "Can't",
 'continue',

$$P(w)=U(w)^{3/4}/Z$$

In [16]:
unigram_table = []

for v in vocabs:
    uw = word_count[v] / num_total_words
    uw_alpha = int((uw ** 0.75) / z)
    unigram_table.extend([v] * uw_alpha)
    
Counter(unigram_table)

Counter({'``': 45,
         "''": 45,
         'one': 22,
         '--': 22,
         'would': 20,
         'said': 17,
         'could': 14,
         'time': 14,
         'two': 12,
         'may': 12,
         'man': 11,
         'like': 11,
         'first': 11,
         'new': 10,
         'also': 10,
         'must': 10,
         'made': 10,
         'Af': 10,
         'back': 10,
         'much': 9,
         'even': 9,
         'years': 9,
         'way': 9,
         'many': 9,
         'get': 8,
         'see': 8,
         'make': 8,
         'little': 8,
         'Mr.': 8,
         'work': 8,
         'people': 8,
         'good': 8,
         'well': 8,
         'still': 8,
         'know': 7,
         'might': 7,
         'came': 7,
         'long': 7,
         'used': 7,
         'us': 7,
         'men': 7,
         'world': 7,
         'year': 7,
         'last': 7,
         'life': 7,
         'never': 7,
         'use': 6,
         'take': 6,
         'New': 6,
         'p

## 4. Model

$$\mathbf{J}_{\text{neg-sample}}(\mathbf{v}_c,o,\mathbf{U})=-\log(\sigma(\mathbf{u}_o^T\mathbf{v}_c))-\sum_{k=1}^K\log(\sigma(-\mathbf{u}_k^T\mathbf{v}_c))$$

In [17]:
def prepare_sequence(seq, word2index):
    idxs = list(map(lambda w: word2index[w] if word2index.get(w) is not None else word2index['<UNK>'], seq))
    return torch.LongTensor(idxs)

In [18]:
import random

def negative_sampling(targets, unigram_table, k):
    batch_size = targets.shape[0]
    neg_samples = []
    for i in range(batch_size):  #(1, k)
        target_index = targets[i].item()
        nsample      = []
        while (len(nsample) < k):
            neg = random.choice(unigram_table)
            if word2index[neg] == target_index:
                continue
            nsample.append(neg)
        neg_samples.append(prepare_sequence(nsample, word2index).reshape(1, -1))
        
    return torch.cat(neg_samples) #batch_size, k

In [19]:
batch_size = 2
x, y = random_batch(batch_size, corpus)
x_tensor = torch.LongTensor(x)
y_tensor = torch.LongTensor(y)

In [20]:
k = 5
neg_samples = negative_sampling(y_tensor, unigram_table, k)

In [21]:
y_tensor[1]

tensor([6247])

In [22]:
neg_samples[1]

tensor([1262, 8441, 4111, 4774, 5166])

$$\mathbf{J}_{\text{neg-sample}}(\mathbf{v}_c,o,\mathbf{U})=-\log(\sigma(\mathbf{u}_o^T\mathbf{v}_c))-\sum_{k=1}^K\log(\sigma(-\mathbf{u}_k^T\mathbf{v}_c))$$

In [23]:
class SkipgramNeg(nn.Module):
    
    def __init__(self, voc_size, emb_size):
        super(SkipgramNeg, self).__init__()
        self.embedding_center  = nn.Embedding(voc_size, emb_size)
        self.embedding_outside = nn.Embedding(voc_size, emb_size)
        self.logsigmoid        = nn.LogSigmoid()
    
    def forward(self, center, outside, negative):
        #center, outside:  (bs, 1)
        #negative       :  (bs, k)
        
        center_embed   = self.embedding_center(center) #(bs, 1, emb_size)
        outside_embed  = self.embedding_outside(outside) #(bs, 1, emb_size)
        negative_embed = self.embedding_outside(negative) #(bs, k, emb_size)
        
        uovc           = outside_embed.bmm(center_embed.transpose(1, 2)).squeeze(2) #(bs, 1)
        ukvc           = -negative_embed.bmm(center_embed.transpose(1, 2)).squeeze(2) #(bs, k)
        ukvc_sum       = torch.sum(ukvc, 1).reshape(-1, 1) #(bs, 1)
        
        loss           = self.logsigmoid(uovc) + self.logsigmoid(ukvc_sum)
        
        return -torch.mean(loss)

In [24]:
#test your model
emb_size = 2
voc_size = len(vocabs)
model = SkipgramNeg(voc_size, emb_size)

In [25]:
loss = model(x_tensor, y_tensor, neg_samples)

In [26]:
loss

tensor(1.9709, grad_fn=<NegBackward0>)

## 5. Training

In [27]:
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [28]:
def epoch_time(start_time, end_time):
    elapsed_time = end_time - start_time
    elapsed_mins = int(elapsed_time / 60)
    elapsed_secs = int(elapsed_time - (elapsed_mins * 60))
    return elapsed_mins, elapsed_secs

In [29]:
start = time.time()
num_epochs = 1000
window_size = 5

for epoch in range(num_epochs):
    
    #get batch
    input_batch, label_batch = random_batch(batch_size, corpus, window_size)
    input_tensor = torch.LongTensor(input_batch)
    label_tensor = torch.LongTensor(label_batch)
    
    #predict
    neg_samples = negative_sampling(label_tensor, unigram_table, k)
    loss = model(input_tensor, label_tensor, neg_samples)
    
    #backprogate
    optimizer.zero_grad()
    loss.backward()
    
    #update alpha
    optimizer.step()

    epoch_mins, epoch_secs = epoch_time(start, time.time())
    
    #print the loss
    if (epoch + 1) % 100 == 0:
        print(f"Epoch: {epoch + 1} | Loss: {loss:.6f} | Time: {epoch_mins}m {epoch_secs}s")

Epoch: 100 | Loss: 1.588514 | Time: 1m 25s
Epoch: 200 | Loss: 3.085959 | Time: 2m 47s
Epoch: 300 | Loss: 1.704542 | Time: 4m 4s
Epoch: 400 | Loss: 1.667598 | Time: 5m 21s
Epoch: 500 | Loss: 2.005045 | Time: 6m 40s
Epoch: 600 | Loss: 1.940446 | Time: 7m 57s
Epoch: 700 | Loss: 0.862773 | Time: 9m 11s
Epoch: 800 | Loss: 3.457966 | Time: 10m 15s
Epoch: 900 | Loss: 1.680911 | Time: 11m 22s
Epoch: 1000 | Loss: 3.272110 | Time: 12m 30s


## 6. Plot the embeddings

In [30]:
vocabs

['assumptions',
 'impossible',
 'Boys',
 'worn',
 'intellectual',
 'Club',
 'Market',
 'French',
 'rope',
 'however',
 'Turkish',
 'stared',
 'sponsored',
 'slipped',
 'proof',
 'age',
 'Dr.',
 'Colorado',
 'emotions',
 'earlier',
 'Nelson',
 'eloquent',
 'playing',
 'register',
 'concepts',
 'Monroe',
 'compiled',
 'One',
 'tremendous',
 'direction',
 'Publications',
 'ordinary',
 'C',
 'Chapel',
 'angle',
 'theology',
 'contributions',
 'era',
 'Academy',
 'vertical',
 'skin',
 'waving',
 'singers',
 'blunt',
 'live',
 'react',
 'Achievement',
 'adjust',
 'lump',
 'Youth',
 'theoretical',
 'springs',
 'selfish',
 'decides',
 'watercolor',
 'remind',
 'Turning',
 'slice',
 'lead',
 'travel',
 'sake',
 'Yes',
 'Joseph',
 'remark',
 'leaders',
 'surrendered',
 'Dumont',
 'supplied',
 'approaching',
 'honors',
 'camera',
 'university',
 'acted',
 'element',
 'neurotic',
 'match',
 'FBI',
 'filtered',
 'consistent',
 'phenomena',
 'brighter',
 'name',
 'H',
 'Gen.',
 "Can't",
 'continue',

In [31]:
fish = torch.LongTensor([word2index['fish']])
fish

tensor([8667])

In [32]:
fish_embed_c = model.embedding_center(fish)
fish_embed_o = model.embedding_outside(fish)
fish_embed   = (fish_embed_c + fish_embed_o) / 2
fish_embed

tensor([[ 0.6047, -0.8883]], grad_fn=<DivBackward0>)

In [33]:
fish_embed_o

tensor([[ 0.4870, -2.2891]], grad_fn=<EmbeddingBackward0>)

In [34]:
def get_embed(word):
    try:
        index = word2index[word]
    except:
        index = word2index['<UNK>']
        
    word = torch.LongTensor([word2index[word]])
    
    embed_c = model.embedding_center(word)
    embed_o = model.embedding_outside(word)
    embed   = (embed_c + embed_o) / 2
    
    return embed[0][0].item(), embed[0][1].item()

In [35]:
get_embed('fruit')

(-1.3676352500915527, 0.11526966840028763)

In [36]:
get_embed('cat')

(0.09021466970443726, 0.2356942594051361)

In [37]:
get_embed('dog')

(-0.9168112277984619, -0.5291646718978882)

In [38]:
get_embed('fish')

(0.6047122478485107, -0.888310432434082)

## 7. Cosine similarity

In [39]:
fish = get_embed('fish')
fish

(0.6047122478485107, -0.888310432434082)

In [40]:
fruit = get_embed('fruit')
fruit

(-1.3676352500915527, 0.11526966840028763)

In [41]:
cat = get_embed('cat')
cat

(0.09021466970443726, 0.2356942594051361)

In [42]:
np.array(fish) @ np.array(cat)

-0.15481575378852597

In [43]:
#more formally is to divide by its norm
def cosine_similarity(A, B):
    dot_product = np.dot(A, B)
    norm_a = np.linalg.norm(A)
    norm_b = np.linalg.norm(B)
    similarity = dot_product / (norm_a * norm_b)
    return similarity

print(cosine_similarity(np.array(fish), np.array(cat)))
print(cosine_similarity(np.array(fish), np.array(fruit)))

-0.5708601653476716
-0.6301688250982604


In [44]:
# Create a pickle of the model
import pickle

with open('../../app/models/skipgram_neg/skipgram_neg.pkl', 'wb') as f:
    pickle.dump(model, f)

with open('../../app/models/skipgram_neg/skipgram_neg_word2index.pkl', 'wb') as f:
    pickle.dump(word2index, f)

with open('../../app/models/skipgram_neg/skipgram_neg_index2word.pkl', 'wb') as f:
    pickle.dump(index2word, f)